import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:safebox/sbox/constants.dart';
import 'package:safebox/sbox/engine/bundle_decryptor.dart';
import 'package:safebox/sbox/engine/bundle_probe.dart';
import 'package:safebox/sbox/format/bundle_header.dart';
import 'package:safebox/sbox/format/sbox_version.dart';
import 'package:safebox/sbox/identity/bip39_identity.dart';

void main() {
  const mnemonic =
      'abandon abandon abandon abandon abandon abandon abandon abandon '
      'abandon abandon abandon about';

  test('Dart reads and decrypts an object generated by the Rust SDK', () async {
    final encoded = await File('test/fixtures/rust_sdk_interop.sbox.b64')
        .readAsString();
    final object = base64Decode(encoded.trim());
    final header = BundleHeader.parse(object);
    expect(header.version, SboxVersion.v31);
    expect(header.isRoot, isTrue);
    expect(header.shardCount, 1);

    final identity = await SboxIdentityDeriver().deriveIdentity(mnemonic);
    try {
      final probe = await BundleProbe.readManifest(
        basename: header.canonicalBasename,
        objectPrefix: object.sublist(0, header.headerLength),
        identity: identity.publicIdentity,
      );
      expect(probe.status, BundleTrustStatus.metadataReadable);
      expect(probe.manifest?.originalName, 'rust-sdk-interop.txt');
      expect(probe.manifest?.mediaType, 'text/plain; charset=utf-8');

      final decrypted = await BundleDecryptor().decryptBytes(
        shardBytes: <List<int>>[object],
        mnemonic: mnemonic,
        expectedIdentity: identity.publicIdentity,
      );
      expect(decrypted.status, BundleTrustStatus.complete);
      expect(decrypted.manifest.contentKind, SboxContentKind.file);
      expect(
        utf8.decode(decrypted.plaintext),
        'Rust SDK → SafeBox 客户端\n'
        'SBOX 3.1 interoperability fixture.\n',
      );
      decrypted.plaintext.fillRange(0, decrypted.plaintext.length, 0);
    } finally {
      identity.disposeControlledSecrets();
      object.fillRange(0, object.length, 0);
    }
  }, timeout: const Timeout(Duration(minutes: 5)));
}
