import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:bip39/bip39.dart' as bip39;
import 'package:crypto/crypto.dart' as crypto;
import 'package:unorm_dart/unorm_dart.dart' as unorm;

import '../bytes.dart';
import '../crypto/secret_bytes.dart';
import '../errors.dart';
import 'der.dart';
import 'hmac_drbg.dart';
import 'primality.dart';
import 'rsa_identity_profile1.dart';
import 'rsa_models.dart';

/// Creates and restores the single RSA Identity Profile 1 supported by the
/// application. New entropy is always generated by [Random.secure].
final class SboxIdentityDeriver {
  SboxIdentityDeriver({Random? secureRandom})
    : _secureRandom = secureRandom ?? Random.secure();

  final Random _secureRandom;

  String generateMnemonic() {
    final entropy = secureRandomBytes(16, random: _secureRandom);
    try {
      return bip39.entropyToMnemonic(hexLower(entropy));
    } finally {
      entropy.fillRange(0, entropy.length, 0);
    }
  }

  String normalizeAndValidateMnemonic(String mnemonic) {
    final normalized = unorm
        .nfkd(mnemonic)
        .trim()
        .split(RegExp(r'\s+'))
        .join(' ');
    final words = normalized.split(' ');
    if (words.length != 12 ||
        words.any((word) => !RegExp(r'^[a-z]+$').hasMatch(word)) ||
        !bip39.validateMnemonic(normalized)) {
      throw const SboxException(
        SboxErrorCode.invalidMnemonic,
        '助记词必须是校验有效的 12 个 BIP39 英文单词',
      );
    }
    return normalized;
  }

  Uint8List deriveBip39Seed(String mnemonic) {
    final normalized = normalizeAndValidateMnemonic(mnemonic);
    return Uint8List.fromList(bip39.mnemonicToSeed(normalized, passphrase: ''));
  }

  Future<Uint8List> deriveRsaDrbgOkm(List<int> bip39Seed) async {
    return _hkdfSha512(
      inputKeyMaterial: bip39Seed,
      salt: ascii.encode(RsaIdentityProfile1.drbgHkdfSalt),
      info: ascii.encode(RsaIdentityProfile1.drbgHkdfInfo),
      length: 48,
    );
  }

  Future<EphemeralIdentity> deriveIdentity(String mnemonic) async {
    final seed = SecretBytes(deriveBip39Seed(mnemonic));
    Uint8List? okm;
    HmacDrbgSha256? drbg;
    try {
      okm = await deriveRsaDrbgOkm(seed.bytes);
      drbg = HmacDrbgSha256(
        entropyInput: okm.sublist(0, 32),
        nonce: okm.sublist(32, 48),
        personalization: asciiBytes(RsaIdentityProfile1.personalization),
      );
      final rsa = DeterministicRsa3072Generator(drbg).generate();
      final spkiDer = encodeRsaSubjectPublicKeyInfo(rsa.privateKey.publicKey);
      final recipientKeyId = sha256Bytes(spkiDer);
      final publicIdentity = PublicIdentity(
        rsaPublicKey: rsa.privateKey.publicKey,
        spkiDer: spkiDer,
        spkiPem: encodePublicKeyPem(spkiDer),
        recipientKeyId: recipientKeyId,
      );
      return EphemeralIdentity(
        publicIdentity: publicIdentity,
        rsaPrivateKey: rsa.privateKey,
        pCandidateCount: rsa.pCandidateCount,
        qCandidateCount: rsa.qCandidateCount,
      );
    } on SboxException {
      rethrow;
    } catch (_) {
      throw const SboxException(
        SboxErrorCode.identityDerivation,
        '身份派生失败；没有生成或保存任何私钥',
      );
    } finally {
      seed.dispose();
      okm?.fillRange(0, okm.length, 0);
      drbg?.dispose();
    }
  }

  static Uint8List _hkdfSha512({
    required List<int> inputKeyMaterial,
    required List<int> salt,
    required List<int> info,
    required int length,
  }) {
    if (length < 0 || length > 255 * 64) {
      throw ArgumentError.value(length, 'length');
    }
    final normalizedSalt = salt.isEmpty ? List<int>.filled(64, 0) : salt;
    final prk = Uint8List.fromList(
      crypto.Hmac(
        crypto.sha512,
        normalizedSalt,
      ).convert(inputKeyMaterial).bytes,
    );
    final output = Uint8List(length);
    var previous = Uint8List(0);
    var written = 0;
    try {
      for (var counter = 1; written < length; counter++) {
        final message = concatBytes(<List<int>>[
          previous,
          info,
          <int>[counter],
        ]);
        final next = Uint8List.fromList(
          crypto.Hmac(crypto.sha512, prk).convert(message).bytes,
        );
        message.fillRange(0, message.length, 0);
        previous.fillRange(0, previous.length, 0);
        previous = next;
        final take = (length - written).clamp(0, previous.length);
        output.setRange(written, written + take, previous);
        written += take;
      }
      return output;
    } finally {
      prk.fillRange(0, prk.length, 0);
      previous.fillRange(0, previous.length, 0);
    }
  }
}
